import client from "./apolloClient"

import {
  ADD_CONTACT_WITH_PHONES,
  ADD_NUMBER_TO_CONTACT,
  DELETE_CONTACT_PHONE,
  EDIT_CONTACT,
  EDIT_PHONE_NUMBER,
  GET_CONTACT_DETAIL,
  GET_CONTACT_LIST,
  GET_PHONE_LIST,
} from "./contact"

export { client }

export {
  ADD_CONTACT_WITH_PHONES,
  ADD_NUMBER_TO_CONTACT,
  DELETE_CONTACT_PHONE,
  EDIT_CONTACT,
  EDIT_PHONE_NUMBER,
  GET_CONTACT_DETAIL,
  GET_CONTACT_LIST,
  GET_PHONE_LIST,
}
